### ISSUE TITLE
Any chance of getting updated?

### ISSUE THREAD

**Issue by MostHated** [maikebing/EntityFrameworkCore.LiteDB#15]
Hey there,
    I would love to make use of this, but I can't seem to find the magic combo of version to target to make it work. I just keep getting errors out of the box, and with anything I have tried so far.

Thanks,
-MH

**Comment by maikebing** [comment]
If it is for .net 5.0, this may require an upgrade.

**Comment by maikebing** [comment]
Currently only available for .Net Core 3.1

**Comment by MostHated** [comment]
Sorry for the late reply, it's no worries, I got something worked out a while back.
